"use client"
import Head from 'next/head'
import {ThemeProvider} from 'styled-components'
import Theme from '../theme/theme'
// components
import MenuPrimeiro from '../component/header/menu/menuPrimeiro'

import MenuSegundo from '../component/header/menu/menuSegundo'


// UI

import { RowBodyCenterC,RowBodyNoCenterC,RowCenterC,RowBetwenC,RowNoCenterC} from '../ui/rowContainer'
import { ColumCenter,ColumNoCenter,ColumBodyNoCenter } from '../ui/columContainer'
import MenuContaner from '../ui/headerC/menuConatainer'
import HeaderContainer from '../ui/headerC/HeaderContainer'
import PesquisaMenuC from '../ui/headerC/pesquisaMenuC'
import PesquisaMenuCFilho from '../ui/headerC/pesquisaMenuCFilho'
import BannerPrincipalC from '../ui/banner/bannerPrincipalC'

import BodyContainer from '../ui/bodyContainer'
// css
import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body> 
            <ThemeProvider theme = {Theme} >
            <BodyContainer>
       <HeaderContainer>
              <MenuContaner>
                <MenuPrimeiro/>
                <MenuSegundo/>
                              </MenuContaner>
             <PesquisaMenuC>
                    <PesquisaMenuCFilho> 

                    </PesquisaMenuCFilho> 
              </PesquisaMenuC>
              </HeaderContainer>
       {children}  
       
        <RowBodyCenterC propriedade={{background:'blue'}} >
            
            <RowBetwenC propriedade={{background:'red'}} >
                                <h1>parte1</h1>   
                        </RowBetwenC>
    </RowBodyCenterC>
   
         <RowBodyCenterC propriedade={{background:'none'}}  >
          <ColumCenter propriedade={{background:'none'}} >
                    <h1>parte 1</h1>
                    
                    <h1>parte 2</h1>
                    </ColumCenter>
                  
          </RowBodyCenterC>
    </BodyContainer>
        </ThemeProvider>
       </body>      

    </html>
  )
}



